package com.bonborunote.niconicoviewer.search.domain

enum class Sort {
  VIEW_COUNT_ASC,
  VIEW_COUNT_DESC,
  MYLIST_COUNT_ASC,
  MYLIST_COUNT_DESC,
  COMMENT_COUNT_ASC,
  COMMENT_COUNT_DESC,
  START_TIME_COUNT_ASC,
  START_TIME_COUNT_DESC,
  LAST_COMMENT_TIME_COUNT_ASC,
  LAST_COMMENT_TIME_COUNT_DESC,
  LENGTH_SECONDS_COUNT_ASC,
  LENGTH_SECONDS_COUNT_DESC
}
